name: Build and Upload Binary

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Package List
        run: sudo apt-get update

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> ~/.profile
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

      - name: Install Arduino CLI
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install arduino-cli

      - name: Compile Sketch
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32
          arduino-cli compile --fqbn esp32:esp32:m5stick-c SonicIoT.ino

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled_binary
          path: .pio/build/m5stick-c/firmware.bin
